version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: sd2developer/api-service-irk
    container_name: sd2-service-irk
    ports:
      - "8040:8040"
    volumes:
      - .:/var/www/publish/container/service-irk
      - ./hosts:/etc/hosts-custom:ro
    restart: always
    extra_hosts:
      - "SD2ONLINELB:103.116.234.13"
      - "SD2ONLINE12:103.116.234.253"
      - "SD2ONLINE14:103.116.234.253"
      - "DBINFRA:103.116.234.253"
      - "SD2ONLINE:103.116.234.253"
      - "SD2ONLINE2:103.116.234.253"
      - "SD2ONLINE1:103.116.234.253"
      - "LBINFRA:103.116.234.13"
      - "LBINFRAPUBLIC:103.116.234.13"

