name: IRK WEBSERVICES CI/CD

on:
  push:
    branches: [main, reza, bayu, kalis, andy]
  pull_request:
    branches: [main, reza, bayu, kalis, andy]
    
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"
          tools: composer:v2

      - name: Copy env.php
        run: php -r "file_exists('env.php') || copy('env.php.example', 'env.php');"

  export-deployment-matrix:
    runs-on: ubuntu-latest
    outputs:
      deployment-matrix: ${{ steps.export-deployment-matrix.outputs.deployment-matrix }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: "Export Deployment Matrix"
        id: export-deployment-matrix
        run: |
          JSON="$(cat ./.github/workflows/ci-cd.json)"
          JSON="${JSON//'%'/'%25'}"
          JSON="${JSON//$'\n'/'%0A'}"
          JSON="${JSON//$'\r'/'%0D'}"
          echo "::set-output name=deployment-matrix::$JSON"
  deploy:
    name: "${{ matrix.server.name }}: Deploy"
    needs: [tests, export-deployment-matrix]
    strategy:
      matrix:
        server: ${{ fromJson(needs.export-deployment-matrix.outputs.deployment-matrix) }}
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' }}
    steps:
      - name: "Deploy to Production Environment"
        if: github.ref == 'refs/heads/main'
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets[matrix.server.ip] }}
          username: ${{ secrets.SERVICE_USERNAME }}
          port: ${{ matrix.server.port }}
          password: ${{ secrets[matrix.server.password] }}
          script: |
            cd /var/www/APIServiceIRK
            git add .
            git commit -m "update"
            git fetch origin main
            git pull --no-ff origin main
            sudo php artisan cache:clear
            php artisan config:cache
            php artisan config:clear
            php artisan route:clear
